/**
 * Generated by scripts/write-instrument.mjs. Do not edit by hand.
 *
 * Run `npm run instrument` after changing package.json or the lockfile. CI verifies
 * that this file matches the installed tree.
 */

export const PACKAGE_VERSION = "0.1.0";

export const DEPENDENCY_VERSIONS: Readonly<Record<string, string>> = Object.freeze(
  {
    "parse5": "7.3.0",
    "axe-core": "4.12.1"
  }
);
